-- Create the leads table if it doesn't exist
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    project_type TEXT,
    description TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone (anon) to insert leads
CREATE POLICY "Enable insert for all users" ON "public"."leads"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

-- Create a policy to allow service role to view leads (optional but good practice)
-- Usually service role bypasses RLS, but explicit policy can be added if needed for authenticated users.
-- For now, we only need INSERT for public.

-- Grant usage on sequence for anon (sometimes needed depending on postgres version/setup)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Grant access to table
GRANT ALL ON TABLE "public"."leads" TO anon;
GRANT ALL ON TABLE "public"."leads" TO authenticated;
GRANT ALL ON TABLE "public"."leads" TO service_role;
